# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

PRE_COMMANDS:
  - command: pip3 install -r requirements.txt
    cwd: "root"
