[project]
name = "netcfgbu"
version = "1.0.0"
description = "Network Configuration Backup"
authors = [
    { name = "Jeremy Schulman" },
    { name = "Ryan Merolle" },
]
requires-python = "~=3.9"
license = "Apache-2.0"
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Networking"
]

dependencies = [
    "aiofiles",
    "asyncssh",
    "toml",
    "pydantic-settings",
    "tabulate",
    "click",
    "first",
    "pexpect",
    "types-tabulate",
    "types-first",
    "types-aiofiles",
    "types-toml",
    "types-pexpect",
    "pydantic==2.7.*",
    "cryptography< 43.0.0",
]

[project.urls]
Repository = "https://github.com/ryanmerolle/netcfgbu"

[project.scripts]
netcfgbu = "netcfgbu.main:main"

[dependency-groups]
dev = [
    "asynctest",
    "pylint",
    "mypy",
    "interrogate",
    "invoke",
    "isort",
    "pre-commit",
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "requests",
    "ruff",
    "sourcery-analytics",
    "tox",
]

[virtualenvs]
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.path = ".venv"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
target-version = ['py39']

[tool.interrogate]
    fail-under = 0
    verbose = 1
    color = true
    ignore-module = true
    exclude = ["setup.py", "tasks.py", "bin"]

[tool.bandit]
exclude_dirs = ["tests"]

[tool.mypy]
python_version = "3.9"
exclude = [
    ".vnenv"
]
